### ISSUE TITLE
SystemError: <built-in function add_font> returned a result with an exception set

### ISSUE THREAD

**Issue by Guillaume-Fgt** [bandit-masked/raccoon#3]
Hi,

I tried to use your player but I had an error. I am on Windows 10. Python 3.10

What I did:
- clone the repo
- created a venv
- pip install -r requirements.txt
- run directly main.py

This is the console message:
```
Exception: Error: [1000] Message:       Font file could not be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\guill\Documents\Python\raccoon\src\main.py", line 126, in <module>
    main()
  File "c:\Users\guill\Documents\Python\raccoon\src\main.py", line 118, in main  
    raccoons, mp, app_state, logo_fader, leaves_button_fader, fire, glow, smoke1, smoke2, particle = setup()
  File "c:\Users\guill\Documents\Python\raccoon\src\main.py", line 14, in setup  
    main_window, logo_window = gui.gui(mp, music_folder, music_files, app_state) 
  File "c:\Users\guill\Documents\Python\raccoon\src\gui\gui.py", line 246, in gui    style.load_fonts()
  File "c:\Users\guill\Documents\Python\raccoon\src\gui\style.py", line 57, in load_fonts
    default_font = dpg.add_font(id='font1', file='fonts/open_sans/opensans_regular.ttf', size=20)
  File "C:\Users\guill\Documents\Python\raccoon\.venv\lib\site-packages\dearpygui\dearpygui.py", line 4155, in add_font
    return internal_dpg.add_font(file, size, label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, parent=parent, **kwargs)
SystemError: <built-in function add_font> returned a result with an exception set
```
I added /src/ at the beginning of each relative path and now it is working.
For example:
```
  default_font = dpg.add_font(
      id="font1", file="src/fonts/open_sans/opensans_regular.ttf", size=20
  )
```
 I did that because using print(os.getcwd()) in main.py, it showed it was working in the "raccoon folder", not the "src" one.

Did I run the app the wrong way?

**Comment by bandit-masked** [comment]
Hi,

Thank you for trying out Raccoon Music Player and letting me know about the error. I think you did everything correctly as far as I can tell. I have written the app on Windows 10, Python 3.8 and 3.9 using PyCharm.

An error like this shouldn't happen of course. I'm not too experienced with these things, but maybe it's due to variability of IDE configuration settings that I'm not aware of. My best guess is that you somehow started the app while the active directory was /raccoon, possibly by running /src/main.py. 

Good to see you got it to run eventually!

Since I have no idea what went wrong, I can't solve it. I'll keep it in mind in case others have similar issues. For now, I'll close the issue.
